### PR TITLE
Fix default vaule of upper_limit and lower_limit.

### PR DESCRIPTION
**Pull request by koichiro**
It does not draw graph using rrdtool-1.5.5.

image

```
11:34:29 web.1     | 2016-03-26 11:34:29 - RuntimeError - RRDtool returns error to draw graph, error: option -u - Cannot convert '' to float:
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/focuslight-0.1.4/lib/focuslight/rrd.rb:255:in `graph'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/focuslight-0.1.4/lib/focuslight/web.rb:433:in `block in <class:Web>'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:562:in `process_client'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:52:in `process_client'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-worker-killer-0.4.4/lib/unicorn/worker_killer.rb:92:in `process_client'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:658:in `worker_loop'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:508:in `spawn_missing_workers'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/lib/unicorn/http_server.rb:132:in `start'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/unicorn-5.0.1/bin/unicorn:126:in `<top (required)>'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/bin/unicorn:23:in `load'
11:34:29 web.1     |    /Users/koichiro/.rbenv/versions/2.3.0/bin/unicorn:23:in `<main>'
```

### CODE REVIEW

**Comment by sonots** [comment]
I think the default should be no lower and upper limit.

@tagomoris Do you have any reasons you set the defut to be 2 at https://github.com/oss-gate/workshop/issues/25#issuecomment-201698407 ?

**Comment by tagomoris** [comment]
I have no idea about it right now, but I think it might be copied from anywhere.

**Comment by koichiro** [comment]
@sonots removed default values in this PR. How is it?

**Comment by sonots** [comment]
We need to investigate the reason why the default was 2.
Does growth forecast set the default to 2?
If so, we should also set the default to 2 for compatibility with growth forecast.

**Comment by koichiro** [comment]
Included in #36

**Pull request closed without merging**
